DROP TABLE MEMBER;
-- MEMBER 테이블 생성
CREATE TABLE MEMBER(
    mID    VARCHAR2(30) PRIMARY KEY,
    mPW   VARCHAR2(30) NOT NULL,
    mNAME VARCHAR2(30) NOT NULL,
    mEMAIL VARCHAR2(30),
    mTEL   VARCHAR2(30) NOT NULL,
    mBIRTH DATE,
    mADDRESS VARCHAR2(30)
);
-- ADMIN 테이블 생성
DROP TABLE ADMIN;
CREATE TABLE ADMIN(
    aID VARCHAR2(30) PRIMARY KEY,
    aPW VARCHAR2(30) NOT NULL,
    aNAME VARCHAR2(30) NOT NULL
);
-- BOARD TABLE 생성
DROP TABLE BOARD;
CREATE TABLE BOARD(
    bID NUMBER(6) PRIMARY KEY NOT NULL,
    mID VARCHAR2(30) REFERENCES MEMBER(mID),
    aID VARCHAR2(30) REFERENCES ADMIN(aID),
    bTITLE VARCHAR2(100) NOT NULL,
    bCONTENT VARCHAR2(1000),
    bHIT NUMBER(6),
    bPW VARCHAR2(50) NOT NULL,
    bGROUP NUMBER(6) NOT NULL,
    bSTEP NUMBER(6) NOT NULL,
    bINDENT NUMBER(6) NOT NULL,
    bIP VARCHAR2(50) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE
);
-- RESTAURANT_INFO 테이블 생성
DROP TABLE RESTAURANT_INFO;
CREATE TABLE RESTAURANT_INFO(
    fID NUMBER(6) PRIMARY KEY NOT NULL,
    mID VARCHAR2(30) REFERENCES MEMBER(mID),
    rNO NUMBER(6) REFERENCES RESTAURANT(rNO),
    fTITLE VARCHAR2(100) NOT NULL,
    fCONTENT VARCHAR2(4000),
    fFILENAME VARCHAR2(100),
    fRDATE DATE DEFAULT SYSDATE,
    fHIT NUMBER(6) NOT NULL,
    fGROUP NUMBER(6) NOT NULL,
    fSTEP NUMBER(6) NOT NULL,
    fINDENT NUMBER(6) NOT NULL,
    fIP VARCHAR2(30) NOT NULL
);
CREATE SEQUENCE RESTAURANT_INFO_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
-- RESTAURANT 테이블 생성
DROP TABLE RESTAURANT;
CREATE TABLE RESTAURANT(
    rNO NUMBER(6) PRIMARY KEY NOT NULL,
    rNAME VARCHAR2(50) NOT NULL,
    cNO VARCHAR2(50) REFERENCES RESTAURANT_CATEGORY(cNO) ON DELETE CASCADE,
    rADDRESS VARCHAR2(50) NOT NULL,
    rTEL VARCHAR2(50) NOT NULL,
    rHOLIDAY VARCHAR2(50) NOT NULL,
    rHOURS VARCHAR2(100) NOT NULL,
    rPARKING VARCHAR2(50) NOT NULL
);
-- RESTAURANT_CATEGORY 테이블 생성
DROP TABLE RESTAURANT_CATEGORY;
CREATE TABLE RESTAURANT_CATEGORY(
    cNO VARCHAR2(50) PRIMARY KEY,
    cFOOD VARCHAR2(50) NOT NULL
);
-- 테이블 체크
SELECT * FROM MEMBER;
SELECT * FROM ADMIN;
SELECT * FROM BOARD;
SELECT * FROM RESTAURANT_INFO;
SELECT * FROM RESTAURANT;
SELECT * FROM RESTAURANT_CATEGORY;

commit;
